### ISSUE TITLE
Column values shifted if first attribute is empty

### ISSUE THREAD

**Issue by Elavarasan83** [IWSLLC/json-csv#10]
If first attribute of a record is empty then column values are shifting.

Input:

var table = [
  {
    "car": "",
    "price": 40000,
    "color": "blue"
  }, {
    "car": "BMW",
    "price": 35000,
    "color": "red"
  }, {
    "car": "Tata",
    "price": 60000,
    "color": "green"
  }
];

output:
CAR,COLOR,PRICE
blue,40000
BMW,red,35000
Tata,green,60000

**Comment by nathanb** [comment]
@Elavarasan83 I added a test for your example. Thanks!
