### ISSUE TITLE
This project has malicious dependency

### ISSUE THREAD

**Issue by ubirajaramneto** [IWSLLC/json-csv#29]
Please check issue: https://github.com/dominictarr/event-stream/issues/116

Someone transferred the ownership of the event-stream repo, and introduced a malicious payload.

Please remove the event-stream version and bump to a newer version.

**Comment by nathanb** [comment]
On it! Thanks @ubirajaramneto

**Comment by nathanb** [comment]
Downgraded event-stream to exactly 3.3.4 until I can drop it. Thanks!
