### ISSUE TITLE
Error: Readable.from is not available in the browser

### ISSUE THREAD

**Issue by AllStackDev1** [IWSLLC/json-csv#36]
<img width="429" alt="image" src="https://user-images.githubusercontent.com/36667083/148652692-bfac003d-2e40-4156-adcd-9e08cd25d011.png">

const csv = await jsonCsv.buffered(items, options)

**Comment by nathanb** [comment]
Thanks @AllStackDev1

Apologies! I don't have notifications setup on this repo. This issue makes sense. My main use-case for this module is Node.JS 10+. However, it's certainly something I'm open to investigating or accepting PR's to resolve. 

After a "recent" reworking to eliminate dependencies and Node < v10, I relied on `Readable.from`, and I'm using streaming under the covers for all methods.

**Comment by nathanb** [comment]
@AllStackDev1 After thinking about this, I decided to build a new core library out there for buffered CSV conversion specifically supporting browsers called [`@iwsio/json-csv-core`](https://github.com/IWSLLC/json-csv-core) (Although I haven't completely tested it yet). Take a peek at this one I just published v0.2.0 (at the time of this comment). I'm going to be consuming it from json-csv soon. It's the same core code. But I polyfilled & transpiled it for browser as well as stripped out streaming, encoding and all of the node specific stuff.

I have a branch coming soon for this package `json-csv@v5` that will consume `@iwsio/json-csv-core` (for easier maintenance). However, I intend to keep this `json-csv` package around for specifically targeting native Node.JS and streaming.

I hope this helps!

**Comment by nathanb** [comment]
Ah, closed when I merged. You can find more info about what I just changed in [my blog post(https://iws.io/2022/json-csv-v5).  But what you need can be found in the [@iwsio/json-csv-core package](https://www.npmjs.com/package/@iwsio/json-csv-core)

**Comment by AllStackDev1** [comment]
Thank you for responding to this issue. I will certainly checkout `@iwsio/json-csv-core`
